### ISSUE TITLE
kubectl config

### ISSUE THREAD

**Issue by t5unamie** [wernight/docker-kubectl#2]
Wish to use this as apart of my integration build.

How does it know what the details are for connecting to the Kubs cluster. I can't see anywhere in this file where you port in the config file in the home directory of the user.

Regards

John

**Comment by wernight** [comment]
By default it doesn't; just like a normal install. So you need to setup either via `gcloud`, or via `kubectl set context`, etc.

**Comment by t5unamie** [comment]
closing old tickets

**Comment by t5unamie** [comment]
closing old tickets
